"""change_recomendacion_fk_to_perfumes_coleccion

Revision ID: 53707cfc0e9b
Revises: 57f1cab4ca41
Create Date: 2026-02-21 14:59:31.505683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53707cfc0e9b'
down_revision: Union[str, Sequence[str], None] = '57f1cab4ca41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clear old FK values (they reference perfumes.id which doesn't exist in perfumes_coleccion)
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE recomendaciones SET perfume_recomendado_id = NULL"))

    op.drop_constraint(op.f('recomendaciones_perfume_recomendado_id_fkey'), 'recomendaciones', type_='foreignkey')
    op.create_foreign_key(None, 'recomendaciones', 'perfumes_coleccion', ['perfume_recomendado_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.create_foreign_key(op.f('recomendaciones_perfume_recomendado_id_fkey'), 'recomendaciones', 'perfumes', ['perfume_recomendado_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
