"""change_perfumista_to_perfumistas_json

Revision ID: 57f1cab4ca41
Revises: 85ef08e99960
Create Date: 2026-02-21 13:40:37.211181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f1cab4ca41'
down_revision: Union[str, Sequence[str], None] = '85ef08e99960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new JSON column
    op.add_column('perfumes_coleccion', sa.Column('perfumistas', sa.JSON(), nullable=True))

    # Migrate existing data: convert "perfumista" text to "perfumistas" JSON array
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE perfumes_coleccion
        SET perfumistas = CASE
            WHEN perfumista IS NULL OR perfumista = '' THEN '[]'::json
            ELSE (
                SELECT json_agg(trim(elem))
                FROM unnest(string_to_array(perfumista, ',')) AS elem
                WHERE trim(elem) != ''
            )
        END
    """))

    # Drop old column
    op.drop_column('perfumes_coleccion', 'perfumista')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfumes_coleccion', sa.Column('perfumista', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('perfumes_coleccion', 'perfumistas')
    # ### end Alembic commands ###
