"""expand_password_reset_token_to_64

Revision ID: 66601d4102d7
Revises: 53707cfc0e9b
Create Date: 2026-02-22 20:45:57.927886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66601d4102d7'
down_revision: Union[str, Sequence[str], None] = '53707cfc0e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
