"""add_coleccion_system

Revision ID: 85ef08e99960
Revises: d8f9e0a1b2c3
Create Date: 2026-02-21 00:18:35.243911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ef08e99960'
down_revision: Union[str, Sequence[str], None] = 'd8f9e0a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colecciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('es_publica', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_colecciones_id'), 'colecciones', ['id'], unique=False)
    op.create_table('perfumes_coleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coleccion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=200), nullable=False),
    sa.Column('perfumista', sa.Text(), nullable=True),
    sa.Column('acordes', sa.JSON(), nullable=True),
    sa.Column('notas', sa.JSON(), nullable=True),
    sa.Column('familia_olfativa', sa.String(length=200), nullable=True),
    sa.Column('concentracion', sa.String(length=100), nullable=True),
    sa.Column('momento_dia', sa.String(length=20), nullable=True),
    sa.Column('estacion', sa.String(length=60), nullable=True),
    sa.Column('cantidad_ml', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('calificacion', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('imagen', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfumes_coleccion_id'), 'perfumes_coleccion', ['id'], unique=False)
    op.create_index(op.f('ix_perfumes_coleccion_nombre'), 'perfumes_coleccion', ['nombre'], unique=False)
    op.create_table('reposiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfume_coleccion_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_ml', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['perfume_coleccion_id'], ['perfumes_coleccion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reposiciones_id'), 'reposiciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reposiciones_id'), table_name='reposiciones')
    op.drop_table('reposiciones')
    op.drop_index(op.f('ix_perfumes_coleccion_nombre'), table_name='perfumes_coleccion')
    op.drop_index(op.f('ix_perfumes_coleccion_id'), table_name='perfumes_coleccion')
    op.drop_table('perfumes_coleccion')
    op.drop_index(op.f('ix_colecciones_id'), table_name='colecciones')
    op.drop_table('colecciones')
    # ### end Alembic commands ###
