"""add_api_usage_tracking_tables

Revision ID: b6ddc54be32b
Revises: ea15f927c795
Create Date: 2025-11-22 20:09:40.265627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ddc54be32b'
down_revision: Union[str, Sequence[str], None] = 'ea15f927c795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_daily_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('successful_calls', sa.Integer(), nullable=True),
    sa.Column('failed_calls', sa.Integer(), nullable=True),
    sa.Column('total_tokens_input', sa.Integer(), nullable=True),
    sa.Column('total_tokens_output', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'api_name', name='unique_daily_api_usage')
    )
    op.create_index(op.f('ix_api_daily_usage_api_name'), 'api_daily_usage', ['api_name'], unique=False)
    op.create_index(op.f('ix_api_daily_usage_date'), 'api_daily_usage', ['date'], unique=False)
    op.create_index(op.f('ix_api_daily_usage_id'), 'api_daily_usage', ['id'], unique=False)
    op.create_table('api_usage_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('is_paid_tier', sa.Boolean(), nullable=True),
    sa.Column('free_daily_limit', sa.Integer(), nullable=True),
    sa.Column('free_monthly_limit', sa.Integer(), nullable=True),
    sa.Column('cost_per_call', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cost_per_1m_tokens_input', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_per_1m_tokens_output', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name')
    )
    op.create_index(op.f('ix_api_usage_config_id'), 'api_usage_config', ['id'], unique=False)
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recomendaciones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_api_name'), 'api_usage_logs', ['api_name'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_created_at'), 'api_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_id'), 'api_usage_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_logs_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_created_at'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_api_name'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_index(op.f('ix_api_usage_config_id'), table_name='api_usage_config')
    op.drop_table('api_usage_config')
    op.drop_index(op.f('ix_api_daily_usage_id'), table_name='api_daily_usage')
    op.drop_index(op.f('ix_api_daily_usage_date'), table_name='api_daily_usage')
    op.drop_index(op.f('ix_api_daily_usage_api_name'), table_name='api_daily_usage')
    op.drop_table('api_daily_usage')
    # ### end Alembic commands ###
