"""Initial migration

Revision ID: b7ecbdfcd3bd
Revises: 
Create Date: 2025-09-28 19:10:44.974924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ecbdfcd3bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('perfumista', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.JSON(), nullable=True),
    sa.Column('acordes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfumes_id'), 'perfumes', ['id'], unique=False)
    op.create_index(op.f('ix_perfumes_marca'), 'perfumes', ['marca'], unique=False)
    op.create_index(op.f('ix_perfumes_nombre'), 'perfumes', ['nombre'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('suscrito', sa.Boolean(), nullable=True),
    sa.Column('consultas_restantes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('perfume_collections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('perfume_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=False),
    sa.Column('hora_evento', sa.Time(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('lugar_nombre', sa.String(length=200), nullable=True),
    sa.Column('lugar_tipo', sa.String(length=20), nullable=True),
    sa.Column('lugar_descripcion', sa.String(length=300), nullable=True),
    sa.Column('ocasion', sa.String(length=200), nullable=True),
    sa.Column('expectativa', sa.String(length=200), nullable=True),
    sa.Column('vestimenta', sa.String(length=200), nullable=True),
    sa.Column('clima_descripcion', sa.String(length=100), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('humedad', sa.Float(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('respuesta_ia', sa.Text(), nullable=True),
    sa.Column('perfume_recomendado_id', sa.Integer(), nullable=True),
    sa.Column('explicacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['perfume_recomendado_id'], ['perfumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendaciones_id'), 'recomendaciones', ['id'], unique=False)
    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_ultima_renovacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origen_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('flow_customer_id', sa.String(length=100), nullable=True),
    sa.Column('renovacion_automatica', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_suscripciones_id'), 'suscripciones', ['id'], unique=False)
    op.create_table('historial_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('suscripcion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_pagos_id'), 'historial_pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_pagos_id'), table_name='historial_pagos')
    op.drop_table('historial_pagos')
    op.drop_index(op.f('ix_suscripciones_id'), table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_recomendaciones_id'), table_name='recomendaciones')
    op.drop_table('recomendaciones')
    op.drop_table('perfume_collections')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_perfumes_nombre'), table_name='perfumes')
    op.drop_index(op.f('ix_perfumes_marca'), table_name='perfumes')
    op.drop_index(op.f('ix_perfumes_id'), table_name='perfumes')
    op.drop_table('perfumes')
    # ### end Alembic commands ###
