"""add_payment_system_models

Revision ID: e2987728f29e
Revises: 4b9f5e6c7d8a
Create Date: 2025-10-27 18:43:47.436521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2987728f29e'
down_revision: Union[str, Sequence[str], None] = '4b9f5e6c7d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('color_boton', sa.String(length=7), nullable=True),
    sa.Column('paises_soportados', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_metodos_pago_id'), 'metodos_pago', ['id'], unique=False)
    op.create_table('paquetes_consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad_consultas', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_anterior', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('destacado', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paquetes_consultas_id'), 'paquetes_consultas', ['id'], unique=False)
    op.create_table('botones_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paquete_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=False),
    sa.Column('url_base', sa.String(length=255), nullable=True),
    sa.Column('parametros_adicionales', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes_consultas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_botones_pago_id'), 'botones_pago', ['id'], unique=False)
    op.create_table('transacciones_consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paquete_consultas_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paquete_consultas_id'], ['paquetes_consultas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_consultas_id'), 'transacciones_consultas', ['id'], unique=False)
    op.create_table('pagos_consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paquete_consultas_id', sa.Integer(), nullable=False),
    sa.Column('boton_pago_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia_externa', sa.String(length=200), nullable=True),
    sa.Column('custom_id', sa.String(length=20), nullable=False),
    sa.Column('datos_pago', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['boton_pago_id'], ['botones_pago.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paquete_consultas_id'], ['paquetes_consultas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_consultas_custom_id'), 'pagos_consultas', ['custom_id'], unique=True)
    op.create_index(op.f('ix_pagos_consultas_id'), 'pagos_consultas', ['id'], unique=False)
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pagos_consultas_id'), table_name='pagos_consultas')
    op.drop_index(op.f('ix_pagos_consultas_custom_id'), table_name='pagos_consultas')
    op.drop_table('pagos_consultas')
    op.drop_index(op.f('ix_transacciones_consultas_id'), table_name='transacciones_consultas')
    op.drop_table('transacciones_consultas')
    op.drop_index(op.f('ix_botones_pago_id'), table_name='botones_pago')
    op.drop_table('botones_pago')
    op.drop_index(op.f('ix_paquetes_consultas_id'), table_name='paquetes_consultas')
    op.drop_table('paquetes_consultas')
    op.drop_index(op.f('ix_metodos_pago_id'), table_name='metodos_pago')
    op.drop_table('metodos_pago')
    # ### end Alembic commands ###
